package menu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import org.junit.jupiter.api.Test;

import menu.*;

/**
 * Test class made by ComTest
 * @version 2021.04.28 14:04:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AteriaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi22 */
  @Test
  public void testRekisteroi22() {    // Ateria: 22
    Ateria keitto = new Ateria(); 
    keitto.rekisteroi(); 
    Ateria keitto2 = new Ateria(); 
    keitto2.rekisteroi(); 
    assertEquals("From: Ateria line: 27", keitto.getAteriaId()+1, keitto2.getAteriaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi40 */
  @Test
  public void testRekisteroi40() {    // Ateria: 40
    Ateria keitto = new Ateria(); 
    keitto.rekisteroi(); 
    Ateria keitto2 = new Ateria(); 
    keitto2.rekisteroi(); 
    assertEquals("From: Ateria line: 45", keitto.getAteriaId()+1, keitto2.getAteriaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNimi85 */
  @Test
  public void testSetNimi85() {    // Ateria: 85
    Ateria salaatti = new Ateria(); 
    salaatti.setNimi("SALAATTI"); 
    assertEquals("From: Ateria line: 88", "Salaatti", salaatti.getNimi()); 
    salaatti.setNimi("salaatti"); 
    assertEquals("From: Ateria line: 90", "Salaatti", salaatti.getNimi()); 
    salaatti.setNimi("SALAATTI  "); 
    assertEquals("From: Ateria line: 92", "Salaatti", salaatti.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetAika107 */
  @Test
  public void testSetAika107() {    // Ateria: 107
    Ateria salaatti = new Ateria(); 
    salaatti.setAika("päivällinen"); 
    assertEquals("From: Ateria line: 110", "päivällinen", salaatti.getAika()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone120 */
  @Test
  public void testClone120() {    // Ateria: 120
    Ateria salaatti = new Ateria(); salaatti.rekisteroi(); salaatti.setNimi("salaatti"); 
    Ateria salaattiKlooni = new Ateria(); 
    try {
    salaattiKlooni = salaatti.clone(); 
    } catch (CloneNotSupportedException e) {
    System.err.println("Kloonaus ei onnistunut!"); 
    }
    salaattiKlooni.setNimi("s"); 
    assertEquals("From: Ateria line: 129", "Salaatti", salaatti.getNimi()); 
    assertEquals("From: Ateria line: 130", "S", salaattiKlooni.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse144 */
  @Test
  public void testParse144() {    // Ateria: 144
    Ateria salaatti = new Ateria(); 
    salaatti.parse("1|Salaatti|iltapala|"); 
    assertEquals("From: Ateria line: 147", "Salaatti", salaatti.getNimi()); 
    assertEquals("From: Ateria line: 148", 1, salaatti.getAteriaId()); 
    assertEquals("From: Ateria line: 149", "iltapala", salaatti.getAika()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString169 */
  @Test
  public void testToString169() {    // Ateria: 169
    Ateria salaatti = new Ateria(); 
    salaatti.rekisteroi(); 
    salaatti.setAika("iltapala"); 
    assertEquals("From: Ateria line: 173", "1||iltapala|", salaatti.toString()); 
    salaatti.setNimi("Salaatti"); 
    assertEquals("From: Ateria line: 175", "1|Salaatti|iltapala|", salaatti.toString()); 
  } // Generated by ComTest END
}