package menu.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.28 15:04:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AteriatTest {



  // Generated by ComTest BEGIN
  /** testLisaa27 */
  @Test
  public void testLisaa27() {    // Ateriat: 27
    Ateriat ateriat = new Ateriat(); 
    Ateria hernekeitto = new Ateria(), sosekeitto = new Ateria(); 
    assertEquals("From: Ateriat line: 30", 0, ateriat.getLkm()); 
    ateriat.lisaa(hernekeitto); assertEquals("From: Ateriat line: 31", 1, ateriat.getLkm()); 
    ateriat.lisaa(sosekeitto); assertEquals("From: Ateriat line: 32", 2, ateriat.getLkm()); 
    ateriat.lisaa(hernekeitto); assertEquals("From: Ateriat line: 33", 3, ateriat.getLkm()); 
    assertEquals("From: Ateriat line: 34", hernekeitto, ateriat.anna(0)); 
    assertEquals("From: Ateriat line: 35", sosekeitto, ateriat.anna(1)); 
    assertEquals("From: Ateriat line: 36", hernekeitto, ateriat.anna(2)); 
    assertEquals("From: Ateriat line: 37", false, ateriat.anna(1) == hernekeitto); 
    assertEquals("From: Ateriat line: 38", true, ateriat.anna(1) == sosekeitto); 
    try {
    assertEquals("From: Ateriat line: 39", hernekeitto, ateriat.anna(3)); 
    fail("Ateriat: 39 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    ateriat.lisaa(hernekeitto); assertEquals("From: Ateriat line: 40", 4, ateriat.getLkm()); 
    ateriat.lisaa(hernekeitto); assertEquals("From: Ateriat line: 41", 5, ateriat.getLkm()); 
    ateriat.lisaa(hernekeitto); assertEquals("From: Ateriat line: 42", 6, ateriat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaPaikkaan62 */
  @Test
  public void testLisaaPaikkaan62() {    // Ateriat: 62
    Ateriat ateriat = new Ateriat(); 
    Ateria hernekeitto = new Ateria(), sosekeitto = new Ateria(); 
    assertEquals("From: Ateriat line: 65", 0, ateriat.getLkm()); 
    ateriat.lisaaPaikkaan(0, hernekeitto); assertEquals("From: Ateriat line: 66", 1, ateriat.getLkm()); 
    ateriat.lisaaPaikkaan(0, sosekeitto); assertEquals("From: Ateriat line: 67", 1, ateriat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna82 */
  @Test
  public void testAnna82() {    // Ateriat: 82
    Ateriat ateriat = new Ateriat(); 
    Ateria hernekeitto = new Ateria(), sosekeitto = new Ateria(); 
    ateriat.lisaa(hernekeitto); 
    ateriat.lisaa(sosekeitto); 
    ateriat.lisaa(hernekeitto); 
    assertEquals("From: Ateriat line: 88", hernekeitto, ateriat.anna(0)); 
    try {
    assertEquals("From: Ateriat line: 89", null, ateriat.anna(3)); 
    fail("Ateriat: 89 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaIdlla104 */
  @Test
  public void testAnnaIdlla104() {    // Ateriat: 104
    Ateriat ateriat = new Ateriat(); 
    Ateria hernekeitto = new Ateria(), sosekeitto = new Ateria(); 
    hernekeitto.rekisteroi(); 
    ateriat.lisaa(hernekeitto); 
    ateriat.lisaa(sosekeitto); 
    assertEquals("From: Ateriat line: 110", hernekeitto, ateriat.annaIdlla(5)); 
    try {
    assertEquals("From: Ateriat line: 111", hernekeitto, ateriat.annaIdlla(6)); 
    fail("Ateriat: 111 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallenna135 */
  @Test
  public void testTallenna135() {    // Ateriat: 135
    Ateriat ateriat = new Ateriat(); 
    Ateria keitto = new Ateria(); keitto.setNimi("keitto"); keitto.setAika("päivällinen"); 
    keitto.rekisteroi(); ateriat.lisaa(keitto); 
    Ateria salaatti = new Ateria(); salaatti.setNimi("salaatti"); salaatti.setAika("iltapala"); 
    salaatti.rekisteroi(); ateriat.lisaa(salaatti); 
    ateriat.setTiedosto("ateriat.dat"); 
    ateriat.tallenna(); 
    try (Scanner fi = new Scanner(new FileInputStream(new File(ateriat.getTiedostonNimi())))) {
    String rivi = fi.nextLine(); 
    String rivi2 = fi.nextLine(); 
    assertEquals("From: Ateriat line: 148", "3|Keitto|päivällinen|", rivi); 
    assertEquals("From: Ateriat line: 149", "4|Salaatti|iltapala|", rivi2); 
    } catch (FileNotFoundException e) {
    System.err.println("Tiedostoa ei löydy"); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta172 */
  @Test
  public void testLueTiedostosta172() {    // Ateriat: 172
    Ateriat ateriat = new Ateriat(); 
    Ateria keitto = new Ateria(); keitto.setNimi("keitto"); keitto.setAika("päivällinen"); 
    keitto.rekisteroi(); ateriat.lisaa(keitto); 
    Ateria salaatti = new Ateria(); salaatti.setNimi("salaatti"); salaatti.setAika("iltapala"); 
    salaatti.rekisteroi(); ateriat.lisaa(salaatti); 
    ateriat.setTiedosto("ateriat.dat"); 
    ateriat.tallenna(); 
    ateriat.lueTiedostosta(); 
    assertEquals("From: Ateriat line: 183", keitto, ateriat.anna(0)); 
    assertEquals("From: Ateriat line: 184", salaatti, ateriat.anna(1)); 
  } // Generated by ComTest END
}