package menu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.28 14:21:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AterianRaakaAineTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi19 */
  @Test
  public void testRekisteroi19() {    // AterianRaakaAine: 19
    AterianRaakaAine pottu = new AterianRaakaAine(); 
    pottu.rekisteroi(); 
    AterianRaakaAine kurkku = new AterianRaakaAine(); 
    kurkku.rekisteroi(); 
    assertEquals("From: AterianRaakaAine line: 24", pottu.getAteriaId() + 1, kurkku.getAteriaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetAteriaId55 */
  @Test
  public void testSetAteriaId55() {    // AterianRaakaAine: 55
    AterianRaakaAine salaatinTomaatti = new AterianRaakaAine(); 
    salaatinTomaatti.setAteriaId(1); 
    assertEquals("From: AterianRaakaAine line: 58", 1, salaatinTomaatti.getAteriaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetRaakaAineId70 */
  @Test
  public void testSetRaakaAineId70() {    // AterianRaakaAine: 70
    AterianRaakaAine salaatinTomaatti = new AterianRaakaAine(); 
    salaatinTomaatti.setRaakaAineId(1); 
    assertEquals("From: AterianRaakaAine line: 73", 1, salaatinTomaatti.getRaakaAineId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone84 */
  @Test
  public void testClone84() {    // AterianRaakaAine: 84
    AterianRaakaAine salaatinTomaatti = new AterianRaakaAine(); 
    salaatinTomaatti.rekisteroi(); salaatinTomaatti.setRaakaAineId(2); 
    AterianRaakaAine tomaatinKlooni = new AterianRaakaAine(); 
    try {
    tomaatinKlooni = salaatinTomaatti.clone(); 
    } catch (CloneNotSupportedException e) {
    System.err.println("Kloonaus ei onnistunut!"); 
    }
    tomaatinKlooni.setRaakaAineId(3); 
    assertEquals("From: AterianRaakaAine line: 94", 2, salaatinTomaatti.getRaakaAineId()); 
    assertEquals("From: AterianRaakaAine line: 95", 3, tomaatinKlooni.getRaakaAineId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse109 */
  @Test
  public void testParse109() {    // AterianRaakaAine: 109
    AterianRaakaAine salaatinTomaatti = new AterianRaakaAine(); 
    salaatinTomaatti.parse("1|1|"); 
    assertEquals("From: AterianRaakaAine line: 112", 1, salaatinTomaatti.getAteriaId()); 
    assertEquals("From: AterianRaakaAine line: 113", 1, salaatinTomaatti.getRaakaAineId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString137 */
  @Test
  public void testToString137() {    // AterianRaakaAine: 137
    AterianRaakaAine salaatinTomaatti = new AterianRaakaAine(); 
    salaatinTomaatti.rekisteroi(); salaatinTomaatti.setRaakaAineId(3); 
    assertEquals("From: AterianRaakaAine line: 140", "1|3|", salaatinTomaatti.toString()); 
  } // Generated by ComTest END
}