package menu.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.28 13:36:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AterioidenRaakaAineetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa27 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa27() throws SailoException {    // AterioidenRaakaAineet: 27
    AterioidenRaakaAineet aterioidenRaakaAineet = new AterioidenRaakaAineet(); 
    AterianRaakaAine makarooni = new AterianRaakaAine(), maito = new AterianRaakaAine(); 
    assertEquals("From: AterioidenRaakaAineet line: 31", 0, aterioidenRaakaAineet.getLkm()); 
    aterioidenRaakaAineet.lisaa(makarooni); assertEquals("From: AterioidenRaakaAineet line: 32", 1, aterioidenRaakaAineet.getLkm()); 
    aterioidenRaakaAineet.lisaa(maito); assertEquals("From: AterioidenRaakaAineet line: 33", 2, aterioidenRaakaAineet.getLkm()); 
    aterioidenRaakaAineet.lisaa(makarooni); assertEquals("From: AterioidenRaakaAineet line: 34", 3, aterioidenRaakaAineet.getLkm()); 
    assertEquals("From: AterioidenRaakaAineet line: 35", makarooni, aterioidenRaakaAineet.anna(0)); 
    assertEquals("From: AterioidenRaakaAineet line: 36", maito, aterioidenRaakaAineet.anna(1)); 
    assertEquals("From: AterioidenRaakaAineet line: 37", makarooni, aterioidenRaakaAineet.anna(2)); 
    assertEquals("From: AterioidenRaakaAineet line: 38", false, aterioidenRaakaAineet.anna(1) == makarooni); 
    assertEquals("From: AterioidenRaakaAineet line: 39", true, aterioidenRaakaAineet.anna(1) == maito); 
    try {
    assertEquals("From: AterioidenRaakaAineet line: 40", makarooni, aterioidenRaakaAineet.anna(3)); 
    fail("AterioidenRaakaAineet: 40 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    aterioidenRaakaAineet.lisaa(makarooni); assertEquals("From: AterioidenRaakaAineet line: 41", 4, aterioidenRaakaAineet.getLkm()); 
    aterioidenRaakaAineet.lisaa(makarooni); assertEquals("From: AterioidenRaakaAineet line: 42", 5, aterioidenRaakaAineet.getLkm()); 
    aterioidenRaakaAineet.lisaa(makarooni); assertEquals("From: AterioidenRaakaAineet line: 43", 6, aterioidenRaakaAineet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPeruuta87 */
  @Test
  public void testPeruuta87() {    // AterioidenRaakaAineet: 87
    AterioidenRaakaAineet ar = new AterioidenRaakaAineet(); 
    AterianRaakaAine aine = new AterianRaakaAine(); 
    ar.lisaa(aine); ar.lisaa(aine); ar.lisaa(aine); 
    assertEquals("From: AterioidenRaakaAineet line: 91", 3, ar.getLkm()); 
    ar.peruuta(); ar.peruuta(); 
    assertEquals("From: AterioidenRaakaAineet line: 93", 1, ar.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallenna104 */
  @Test
  public void testTallenna104() {    // AterioidenRaakaAineet: 104
    AterioidenRaakaAineet atrt = new AterioidenRaakaAineet(); 
    AterianRaakaAine keitonPeruna = new AterianRaakaAine(); keitonPeruna.setAteriaId(1); keitonPeruna.setRaakaAineId(5); 
    atrt.lisaa(keitonPeruna); 
    AterianRaakaAine muussinPeruna = new AterianRaakaAine(); muussinPeruna.setAteriaId(2); muussinPeruna.setRaakaAineId(5); 
    atrt.lisaa(muussinPeruna); 
    atrt.setTiedosto("aterioidenraakaaineet.dat"); 
    atrt.tallenna(); 
    try (Scanner fi = new Scanner(new FileInputStream(new File(atrt.getTiedostonNimi())))) {
    String rivi = fi.nextLine(); 
    String rivi2 = fi.nextLine(); 
    assertEquals("From: AterioidenRaakaAineet line: 117", "1|5|", rivi); 
    assertEquals("From: AterioidenRaakaAineet line: 118", "2|5|", rivi2); 
    } catch (FileNotFoundException e) {
    System.err.println("Tiedostoa ei löydy"); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta142 */
  @Test
  public void testLueTiedostosta142() {    // AterioidenRaakaAineet: 142
    AterioidenRaakaAineet atrt = new AterioidenRaakaAineet(); 
    AterianRaakaAine keitonPeruna = new AterianRaakaAine(); keitonPeruna.setAteriaId(1); keitonPeruna.setRaakaAineId(5); 
    atrt.lisaa(keitonPeruna); 
    AterianRaakaAine muussinPeruna = new AterianRaakaAine(); muussinPeruna.setAteriaId(2); muussinPeruna.setRaakaAineId(5); 
    atrt.lisaa(muussinPeruna); 
    atrt.setTiedosto("aterioidenraakaaineet.dat"); 
    atrt.tallenna(); 
    atrt.lueTiedostosta(); 
    assertEquals("From: AterioidenRaakaAineet line: 153", keitonPeruna, atrt.anna(0)); 
    assertEquals("From: AterioidenRaakaAineet line: 154", muussinPeruna, atrt.anna(1)); 
  } // Generated by ComTest END
}