package menu.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.27 14:42:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RaakaAineetTest {



  // Generated by ComTest BEGIN
  /** testLisaa27 */
  @Test
  public void testLisaa27() {    // RaakaAineet: 27
    RaakaAineet r = new RaakaAineet(); 
    RaakaAine kurkku = new RaakaAine(), tomaatti = new RaakaAine(); 
    assertEquals("From: RaakaAineet line: 30", 0, r.getLkm()); 
    r.lisaa(kurkku); assertEquals("From: RaakaAineet line: 31", 1, r.getLkm()); 
    r.lisaa(tomaatti); assertEquals("From: RaakaAineet line: 32", 2, r.getLkm()); 
    r.lisaa(kurkku); assertEquals("From: RaakaAineet line: 33", 3, r.getLkm()); 
    assertEquals("From: RaakaAineet line: 34", kurkku, r.anna(0)); 
    assertEquals("From: RaakaAineet line: 35", tomaatti, r.anna(1)); 
    assertEquals("From: RaakaAineet line: 36", kurkku, r.anna(2)); 
    try {
    assertEquals("From: RaakaAineet line: 37", kurkku, r.anna(3)); 
    fail("RaakaAineet: 37 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    r.lisaa(kurkku); assertEquals("From: RaakaAineet line: 38", 4, r.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallenna101 */
  @Test
  public void testTallenna101() {    // RaakaAineet: 101
    RaakaAineet aineet = new RaakaAineet(); 
    RaakaAine tomaatti = new RaakaAine(); tomaatti.setNimi("tomaatti"); tomaatti.setTyyppiId(3); 
    tomaatti.rekisteroi(); aineet.lisaa(tomaatti); 
    RaakaAine kurkku = new RaakaAine(); kurkku.setNimi("kurkku"); kurkku.setTyyppiId(3); 
    kurkku.rekisteroi(); aineet.lisaa(kurkku); 
    aineet.setTiedosto("raakaaineet.dat"); 
    aineet.tallenna(); 
    try (Scanner fi = new Scanner(new FileInputStream(new File(aineet.getTiedostonNimi())))) {
    String rivi = fi.nextLine(); 
    String rivi2 = fi.nextLine(); 
    assertEquals("From: RaakaAineet line: 114", "102|tomaatti|3|", rivi); 
    assertEquals("From: RaakaAineet line: 115", "103|kurkku|3|", rivi2); 
    } catch (FileNotFoundException e) {
    System.err.println("Tiedostoa ei löydy"); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta138 */
  @Test
  public void testLueTiedostosta138() {    // RaakaAineet: 138
    RaakaAineet aineet = new RaakaAineet(); 
    RaakaAine tomaatti = new RaakaAine(); tomaatti.setNimi("tomaatti"); tomaatti.setTyyppiId(3); 
    tomaatti.rekisteroi(); aineet.lisaa(tomaatti); 
    RaakaAine kurkku = new RaakaAine(); kurkku.setNimi("kurkku"); kurkku.setTyyppiId(3); 
    kurkku.rekisteroi(); aineet.lisaa(kurkku); 
    aineet.setTiedosto("raakaaineet.dat"); 
    aineet.tallenna(); 
    aineet.lueTiedostosta(); 
    assertEquals("From: RaakaAineet line: 149", tomaatti, aineet.anna(0)); 
    assertEquals("From: RaakaAineet line: 150", kurkku, aineet.anna(1)); 
  } // Generated by ComTest END
}