package menu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.28 14:39:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RaakaAineenTyyppiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi21 */
  @Test
  public void testRekisteroi21() {    // RaakaAineenTyyppi: 21
    RaakaAineenTyyppi liha = new RaakaAineenTyyppi(); 
    liha.rekisteroi(); 
    RaakaAineenTyyppi vege = new RaakaAineenTyyppi(); 
    vege.rekisteroi(); 
    assertEquals("From: RaakaAineenTyyppi line: 26", liha.getTyyppiId()+1, vege.getTyyppiId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone73 */
  @Test
  public void testClone73() {    // RaakaAineenTyyppi: 73
    RaakaAineenTyyppi kasvis = new RaakaAineenTyyppi(); 
    kasvis.rekisteroi(); kasvis.setNimi("kasvis"); 
    RaakaAineenTyyppi kasvisKlooni = new RaakaAineenTyyppi(); 
    try {
    kasvisKlooni = kasvis.clone(); 
    } catch (CloneNotSupportedException e) {
    System.err.println("Kloonaus ei onnistunut!"); 
    }
    kasvisKlooni.setNimi("s"); 
    assertEquals("From: RaakaAineenTyyppi line: 83", "kasvis", kasvis.getNimi()); 
    assertEquals("From: RaakaAineenTyyppi line: 84", "s", kasvisKlooni.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse98 */
  @Test
  public void testParse98() {    // RaakaAineenTyyppi: 98
    RaakaAineenTyyppi kasvis = new RaakaAineenTyyppi(); 
    kasvis.parse("1|kasvis|lisuke|"); 
    assertEquals("From: RaakaAineenTyyppi line: 101", "kasvis", kasvis.getNimi()); 
    assertEquals("From: RaakaAineenTyyppi line: 102", 1, kasvis.getTyyppiId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString123 */
  @Test
  public void testToString123() {    // RaakaAineenTyyppi: 123
    RaakaAineenTyyppi kasvis = new RaakaAineenTyyppi(); 
    kasvis.rekisteroi(); 
    kasvis.setOsa("lisuke"); 
    assertEquals("From: RaakaAineenTyyppi line: 127", "1||lisuke|", kasvis.toString()); 
    kasvis.setNimi("kasvis"); 
    assertEquals("From: RaakaAineenTyyppi line: 129", "1|kasvis|lisuke|", kasvis.toString()); 
  } // Generated by ComTest END
}