package menu.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.27 17:37:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RaakaAineidenTyypitTest {



  // Generated by ComTest BEGIN
  /** testLisaa37 */
  @Test
  public void testLisaa37() {    // RaakaAineidenTyypit: 37
    RaakaAineidenTyypit r = new RaakaAineidenTyypit(); 
    RaakaAineenTyyppi vege = new RaakaAineenTyyppi(), liha = new RaakaAineenTyyppi(); 
    assertEquals("From: RaakaAineidenTyypit line: 40", 0, r.getLkm()); 
    r.lisaa(vege); assertEquals("From: RaakaAineidenTyypit line: 41", 1, r.getLkm()); 
    r.lisaa(liha); assertEquals("From: RaakaAineidenTyypit line: 42", 2, r.getLkm()); 
    r.lisaa(vege); assertEquals("From: RaakaAineidenTyypit line: 43", 3, r.getLkm()); 
    assertEquals("From: RaakaAineidenTyypit line: 44", vege, r.anna(0)); 
    assertEquals("From: RaakaAineidenTyypit line: 45", liha, r.anna(1)); 
    assertEquals("From: RaakaAineidenTyypit line: 46", vege, r.anna(2)); 
    try {
    assertEquals("From: RaakaAineidenTyypit line: 47", vege, r.anna(3)); 
    fail("RaakaAineidenTyypit: 47 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    r.lisaa(liha); assertEquals("From: RaakaAineidenTyypit line: 48", 4, r.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallenna95 */
  @Test
  public void testTallenna95() {    // RaakaAineidenTyypit: 95
    RaakaAineidenTyypit tyypit = new RaakaAineidenTyypit(); 
    RaakaAineenTyyppi kasvis = new RaakaAineenTyyppi(); kasvis.setNimi("kasvis"); kasvis.setOsa("lisuke"); 
    kasvis.rekisteroi(); tyypit.lisaa(kasvis); 
    RaakaAineenTyyppi peruna = new RaakaAineenTyyppi(); peruna.setNimi("peruna"); peruna.setOsa("lisuke"); 
    peruna.rekisteroi(); tyypit.lisaa(peruna); 
    tyypit.setTiedosto("tyypit.dat"); 
    tyypit.tallenna(); 
    try (Scanner fi = new Scanner(new FileInputStream(new File(tyypit.getTiedostonNimi())))) {
    String rivi = fi.nextLine(); 
    String rivi2 = fi.nextLine(); 
    assertEquals("From: RaakaAineidenTyypit line: 108", "3|kasvis|lisuke|", rivi); 
    assertEquals("From: RaakaAineidenTyypit line: 109", "4|peruna|lisuke|", rivi2); 
    } catch (FileNotFoundException e) {
    System.err.println("Tiedostoa ei löydy"); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta132 */
  @Test
  public void testLueTiedostosta132() {    // RaakaAineidenTyypit: 132
    RaakaAineidenTyypit tyypit = new RaakaAineidenTyypit(); 
    RaakaAineenTyyppi kasvis = new RaakaAineenTyyppi(); kasvis.setNimi("kasvis"); kasvis.setOsa("lisuke"); 
    kasvis.rekisteroi(); tyypit.lisaa(kasvis); 
    RaakaAineenTyyppi peruna = new RaakaAineenTyyppi(); peruna.setNimi("peruna"); peruna.setOsa("lisuke"); 
    peruna.rekisteroi(); tyypit.lisaa(peruna); 
    tyypit.setTiedosto("tyypit.dat"); 
    tyypit.tallenna(); 
    tyypit.lueTiedostosta(); 
    assertEquals("From: RaakaAineidenTyypit line: 143", kasvis, tyypit.anna(0)); 
    assertEquals("From: RaakaAineidenTyypit line: 144", peruna, tyypit.anna(1)); 
  } // Generated by ComTest END
}