package menu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import menu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.04 13:30:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RaakaAineTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi21 */
  @Test
  public void testRekisteroi21() {    // RaakaAine: 21
    RaakaAine tomaatti = new RaakaAine(); 
    tomaatti.rekisteroi(); 
    RaakaAine kurkku = new RaakaAine(); 
    kurkku.rekisteroi(); 
    assertEquals("From: RaakaAine line: 26", tomaatti.getRaakaAineenId()+1, kurkku.getRaakaAineenId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testClone83 */
  @Test
  public void testClone83() {    // RaakaAine: 83
    RaakaAine salaatti = new RaakaAine(); salaatti.rekisteroi(); salaatti.setNimi("salaatti"); 
    RaakaAine salaattiKlooni = new RaakaAine(); 
    try {
    salaattiKlooni = salaatti.clone(); 
    } catch (CloneNotSupportedException e) {
    System.err.println("Kloonaus ei onnistunut!"); 
    }
    salaattiKlooni.setNimi("s"); 
    assertEquals("From: RaakaAine line: 92", "salaatti", salaatti.getNimi()); 
    assertEquals("From: RaakaAine line: 93", "s", salaattiKlooni.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse107 */
  @Test
  public void testParse107() {    // RaakaAine: 107
    RaakaAine salaatti = new RaakaAine(); 
    salaatti.parse("1|Salaatti|2|"); 
    assertEquals("From: RaakaAine line: 110", "Salaatti", salaatti.getNimi()); 
    assertEquals("From: RaakaAine line: 111", 2, salaatti.getTyyppiId()); 
    assertEquals("From: RaakaAine line: 112", 1, salaatti.getRaakaAineenId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString140 */
  @Test
  public void testToString140() {    // RaakaAine: 140
    RaakaAine salaatti = new RaakaAine(); 
    salaatti.rekisteroi(); 
    salaatti.setTyyppiId(3); 
    assertEquals("From: RaakaAine line: 144", "100||3|", salaatti.toString()); 
    salaatti.setNimi("salaatti"); 
    assertEquals("From: RaakaAine line: 146", "100|salaatti|3|", salaatti.toString()); 
  } // Generated by ComTest END
}